### ISSUE TITLE
Error: 'object' does not contain a definition for 'ExportResultStringPart'

### ISSUE THREAD

**Issue by nitinchawda** [ignatandrei/Exporter#45]
Test Outcome:	Failed
Result StackTrace:	
at CallSite.Target(Closure , CallSite , Object , Object , KeyValuePair`2[] )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at ExportImplementation.ExportExcel2007`1.ExportResultStringPartNotGeneric(IList data, KeyValuePair`2[] additionalData)
   at ExportImplementation.ExportExcel2007`1.ExportMultipleSheets(IList[] data, KeyValuePair`2[] additionalData)

This happens when i ran your example for ExportMultipleSheet Example. Need help on this

**Comment by ignatandrei** [comment]
Hello.  The source code is here. Could you debug it ?
